/** Texts for the signing application only. Add another locale to epotpisTranslations when needed. */
const hr = {
  "metaTitle": "MET ePotpis",
  "metaDescription": "Pregled i potpis ugovora o posredovanju.",
  "app": {
    "brand": "MET",
    "myProfile": "Moj profil",
    "authNotConfigured": "Prijava još nije postavljena. Obratite se osobi koja održava aplikaciju.",
    "title": "Pregled ugovora",
    "newContract": "Novi ugovor",
    "contracts": "Svi ugovori",
    "emptyTitle": "Sve počinje prvim ugovorom.",
    "emptyDescription": "Unesite podatke, pregledajte dokument i pošaljite link vlasniku.",
    "all": "Sve",
    "sent": "POSLAN",
    "signed": "POTPISAN",
    "revoked": "POVUČEN",
    "failed": "GREŠKA IZRADE",
    "expired": "ISTEKAO",
    "owner": "Nalogodavac",
    "property": "Nekretnina",
    "status": "Status",
    "createdAt": "Datum izrade",
    "actions": "Radnje",
    "open": "Otvoreno posredovanje",
    "exclusive": "Isključivo posredovanje",
    "contractType": "Vrsta posredovanja",
    "consumer": "Nalogodavac je potrošač",
    "yes": "Da",
    "no": "Ne",
    "ownerSection": "01 / Podaci nalogodavca",
    "propertySection": "02 / Nekretnina i najam",
    "agreementSection": "03 / Mjesto i datum",
    "ownerName": "Ime i prezime / naziv",
    "oib": "OIB",
    "ownerAddress": "Adresa nalogodavca",
    "phone": "Telefon",
    "email": "E-pošta nalogodavca",
    "propertyAddress": "Adresa nekretnine",
    "descriptionField": "Opis, površina i pripadci nekretnine",
    "rent": "Ciljana mjesečna najamnina (EUR)",
    "deposit": "Polog (EUR)",
    "duration": "Planirano trajanje najma",
    "landRegistry": "ZK podaci",
    "place": "Mjesto sklapanja",
    "date": "Datum ugovora",
    "signerName": "Ime i prezime / funkcija ispod potpisa",
    "preview": "Pregledaj ugovor",
    "send": "POŠALJI",
    "cancel": "Odustani",
    "back": "Natrag",
    "copyLink": "Kopiraj link",
    "copied": "Link je kopiran.",
    "viewDocument": "Otvori ugovor",
    "download": "Preuzmi PDF",
    "revoke": "Povuci link",
    "confirmRevoke": "Povući link za potpis? Broj i dokument ostaju trajno spremljeni.",
    "retryEmail": "Ponovi slanje emaila",
    "signatureSettings": "Potpis posrednika",
    "signatureDescription": "Ovdje nacrtajte ili učitajte svoj stvarni potpis i spremite ga. Ako je spremljen testni potpis, zamijenite ga prije izrade ugovora.",
    "saveSignature": "Spremi potpis",
    "signatureSaved": "Potpis posrednika je spremljen.",
    "signatureRequired": "Molimo dodajte potpis prije nastavka.",
    "drawSignature": "Vaš potpis",
    "clearSignature": "Obriši potpis",
    "uploadSignature": "Učitaj PNG (do 500 kB)",
    "loginTitle": "Vaš prostor za ugovore.",
    "password": "Lozinka",
    "login": "Prijavi se",
    "logout": "Odjavi se",
    "signTitle": "Vaš ugovor je spreman.",
    "signDescription": "Pregledajte ugovor, potpišite se u polje ispod i potvrdite potpis.",
    "reviewTitle": "Pregled dokumenta",
    "signAction": "POTPIŠI",
    "signing": "Spremamo vaš potpis…",
    "signedTitle": "Ugovor je potpisan.",
    "signedDescription": "Hvala vam. Vaš potpis i završni dokument su spremljeni.",
    "signedAt": "Datum i vrijeme potpisa",
    "invalidTitle": "Ovaj link nije dostupan.",
    "invalidDescription": "Link je istekao, povučen ili nije ispravan. Javite se osobi koja vam ga je poslala.",
    "consent": "Pročitao/la sam ugovor i priložene Opće uvjete poslovanja i Cjenik te ih prihvaćam. Potpisujem prikazani dokument.",
    "consumerConsent": "Primio/la sam Obavijest potrošaču. Izričito zahtijevam početak usluge prije isteka 14 dana i potvrđujem da gubim pravo na jednostrani raskid ako je usluga u potpunosti ispunjena.",
    "consentRequired": "Potvrdite izjave uz potpis.",
    "signatureLabel": "Polje za vlastoručni potpis",
    "signatureHint": "Potpišite se prstom ili mišem",
    "documentLoading": "Učitavamo vaš dokument…",
    "documentError": "Dokument se nije učitao. Osvježite stranicu i pokušajte ponovno.",
    "zoomIn": "Povećaj dokument",
    "zoomOut": "Smanji dokument",
    "page": "Stranica",
    "error": "Nešto nije uspjelo. Pokušajte ponovno.",
    "validationError": "Provjerite unesene podatke, duljinu polja i datum ugovora.",
    "authError": "Lozinka nije ispravna ili je prijava istekla.",
    "rateLimited": "Previše pokušaja. Pokušajte ponovno za nekoliko minuta.",
    "conflict": "Dokument je već potpisan, povučen ili izmijenjen. Osvježite stranicu.",
    "loading": "Učitavanje…",
    "saving": "Spremanje…",
    "createdNotice": "Ugovor je spremljen. Link je spreman za dijeljenje.",
    "unsentEmail": "Email nije poslan",
    "deliveredEmail": "Email predan servisu za slanje",
    "failedEmail": "Email nije poslan",
    "pendingEmail": "Email čeka slanje",
    "invitationSubject": "MET - ugovor za potpis",
    "invitationBody": "Poštovani,\n\nvaš ugovor spreman je za pregled i potpis.\n\nOtvorite ugovor za pregled i potpis:\n{link}\n\nNakon potpisivanja primit ćete završni PDF ugovora emailom. Za sva pitanja stojim vam na raspolaganju.\n\nSrdačan pozdrav,\nMaja Mara\nLicencirani agent za nekretnine\nMET d.o.o.\nSavska cesta 32, 10000 Zagreb\n+385 91 606 0866\nmaja@metnekretnine.hr\nhttps://metnekretnine.hr",
    "signedSubject": "MET - potpisani ugovor",
    "signedBody": "Poštovani,\n\nhvala vam. Ugovor uspješno je potpisan {signedAt}.\n\nU privitku se nalazi završni PDF potpisanog ugovora. Molimo sačuvajte ga za svoju evidenciju.\n\nPotpisani ugovor možete otvoriti i putem poveznice:\n{link}\n\nZa sva pitanja stojim vam na raspolaganju.\n\nSrdačan pozdrav,\nMaja Mara\nLicencirani agent za nekretnine\nMET d.o.o.\nSavska cesta 32, 10000 Zagreb\n+385 91 606 0866\nmaja@metnekretnine.hr\nhttps://metnekretnine.hr",
    "brokerSignedSubject": "Potpisan ugovor - {name}",
    "brokerSignedBody": "Poštovana Maja,\n\nUgovor za {name} uspješno je potpisan.\n\nDatum i vrijeme potpisa: {signedAt}\n\nZavršni PDF potpisanog ugovora nalazi se u privitku i spremljen je u aplikaciji.\n\nPregled potpisanog ugovora:\n{link}\n\nMET ePotpis\nMET d.o.o.\nSavska cesta 32, 10000 Zagreb\nhttps://metnekretnine.hr",
    "pdfSignedAt": "Elektronički potpis nalogodavca: {signedAt} (Europe/Zagreb)",
    "pdfFingerprint": "SHA-256 dokumenta prije potpisa: {hash}",
    "previewTitle": "Provjerite podatke prije slanja.",
    "previewDescription": "Provjerite podatke i potpis posrednika prije slanja. Poslani dokument ostaje sačuvan u izvornom obliku.",
    "previewNumber": "PREGLED",
    "search": "Pretraži ugovore…",
    "noResults": "Nema ugovora za ovaj odabir.",
    "signatureUploadError": "Učitajte PNG potpisa do 500 kB, najvećih dimenzija 2048 × 2048 px.",
    "notConfigured": "Alat još nije konfiguriran. Provjerite postavke ePotpisa na poslužitelju.",
    "reviewRequired": "Pričekajte da se dokument učita prije potvrde potpisa.",
    "settings": "Postavke",
    "currentSignature": "Trenutni potpis",
    "currentSignatureDescription": "Potpis se umeće kada prijavljeni administrator izradi pregled i pošalje novi ugovor. Zamjena ili brisanje potpisa ne mijenja već poslane ni potpisane PDF-ove.",
    "replaceSignature": "Zamijeni trenutni potpis",
    "replacementSignature": "Novi potpis",
    "passwordPlaceholder": "Unesite lozinku",
    "ownerNamePlaceholder": "Ime i prezime ili naziv tvrtke",
    "oibPlaceholder": "11 znamenki",
    "ownerAddressPlaceholder": "Ulica i broj, poštanski broj i grad",
    "phonePlaceholder": "+385 91 123 4567",
    "emailPlaceholder": "ime@primjer.hr",
    "signerNamePlaceholder": "Ime i prezime, funkcija ako je primjenjivo",
    "propertyAddressPlaceholder": "Ulica i broj, kat, grad",
    "descriptionFieldPlaceholder": "Npr. stan 64 m², dvije sobe, balkon i spremište",
    "landRegistryPlaceholder": "Npr. k.o. Zagreb, zk. ul. 1234, k.č. 567/8",
    "rentPlaceholder": "Npr. 950",
    "depositPlaceholder": "Npr. 1900",
    "durationPlaceholder": "Npr. 12 mjeseci",
    "placePlaceholder": "Npr. Zagreb",
    "datePlaceholder": "dd.mm.gggg.",
    "oibInvalid": "OIB nije ispravan. Provjerite svih 11 znamenki i kontrolnu znamenku.",
    "deleteContract": "Obriši ugovor",
    "deleteContractTitle": "Obrisati ugovor?",
    "deleteContractDescription": "Ugovor, njegovi PDF-ovi i povezani podaci bit će uklonjeni iz aplikacije. Poveznica više neće raditi. Već poslani emailovi i preuzeti primjerci ostaju kod primatelja.",
    "deleteContractConfirmationLabel": "Za potvrdu upišite OBRIŠI OVAJ UGOVOR",
    "deleteContractConfirmationPlaceholder": "OBRIŠI OVAJ UGOVOR",
    "deleteContractConfirmationError": "Upišite točno OBRIŠI OVAJ UGOVOR kako biste potvrdili brisanje.",
    "contractDeleted": "Ugovor je obrisan.",
    "deleteSignature": "Obriši potpis",
    "deleteSignatureTitle": "Obrisati spremljeni potpis?",
    "deleteSignatureDescription": "Za slanje novih ugovora trebat ćete spremiti novi potpis. Potpisi u postojećim ugovorima ostaju sačuvani.",
    "signatureDeleted": "Spremljeni potpis je obrisan.",
    "deleting": "Brisanje…",
    "deletionBusy": "Email za ovaj ugovor upravo se šalje. Pričekajte trenutak pa ponovite brisanje.",
    "emailSignButton": "Pregledaj i potpiši ugovor",
    "emailSignedButton": "Otvori potpisani ugovor",
    "emailLinkFallback": "Ako gumb ne radi, kliknite na poveznicu ispod ili je kopirajte u preglednik:",
    "addCoOwner": "Dodaj drugog Nalogodavca",
    "removeCoOwner": "Ukloni drugog Nalogodavca",
    "coOwnerSection": "Drugi Nalogodavac",
    "coOwnerDescription": "Obje osobe bit će navedene na istom ugovoru. Svaka unosi svoj potpis, a ugovor se potvrđuje jednom. Poziv i završni PDF šalju se na email prvog Nalogodavca.",
    "pdfContentTooLong": "Uneseni podaci ne stanu u predložak ugovora. Skratite opis ili druge duge unose i ponovno otvorite pregled.",
    "signatureFor": "Potpis - {name}",
    "signatureStep": "Potpis {current} od {total}",
    "signatureRotateHint": "Za lakše potpisivanje okrenite uređaj vodoravno.",
    "signatureExpand": "Proširi prostor za potpis",
    "signatureCollapse": "Natrag na ugovor",
    "confirmSignature": "Prihvati potpis",
    "editSignature": "Zamijeni potpis",
    "signaturePending": "Čeka potpis",
    "signatureReady": "Potpis unesen",
    "signatureReview": "Provjerite potpise pa potvrdite ugovor."
  }
};

export type EPotpisTexts = typeof hr.app;
export type EPotpisPageTexts = typeof hr;
export const epotpisTranslations: Record<string, EPotpisPageTexts> = { hr };

/** Untranslated locales use Croatian until a complete translation is added. */
export function getEPotpisTexts(locale = "hr"): EPotpisPageTexts {
  return epotpisTranslations[locale] ?? epotpisTranslations.hr;
}
