import { defineField, defineType } from "sanity";

export const listingDetailsPage = defineType({
  name: "listingDetailsPage",
  title: "Listing Details Page",
  type: "document",
  fieldsets: [
    {
      name: "price",
      title: "Cijena",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "specs",
      title: "Specifikacije",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "rooms",
      title: "Oznake broja soba",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "agent",
      title: "Agent",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "content",
      title: "Sadržaj",
      options: { collapsible: true, collapsed: false },
    },
  ],
  fields: [
    defineField({
      name: "rentPriceLabel",
      title: "Rent Price Label (e.g. Mjesečni najam)",
      type: "localeString",
      fieldset: "price",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "areaLabel",
      title: "Area Label (e.g. Površina)",
      type: "localeString",
      fieldset: "specs",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "districtLabel",
      title: "District Label (e.g. Kvart)",
      type: "localeString",
      fieldset: "specs",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "roomsLabel",
      title: "Rooms Label (e.g. Broj soba)",
      type: "localeString",
      fieldset: "specs",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heatingLabel",
      title: "Heating Label (e.g. Grijanje)",
      type: "localeString",
      fieldset: "specs",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "availabilityLabel",
      title: "Availability Label (e.g. Dostupnost)",
      type: "localeString",
      fieldset: "specs",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "petFriendlyLabel",
      title: "Pet Friendly Label",
      type: "localeString",
      fieldset: "specs",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "floorLabel",
      title: "Floor Label (e.g. Kat)",
      type: "localeString",
      fieldset: "specs",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "basementLabel",
      title: "Basement Label (e.g. Suteren)",
      type: "localeString",
      fieldset: "specs",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "groundFloorLabel",
      title: "Ground Floor Label (e.g. Prizemlje)",
      type: "localeString",
      fieldset: "specs",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "highGroundFloorLabel",
      title: "High Ground Floor Label (e.g. Visoko prizemlje)",
      type: "localeString",
      fieldset: "specs",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "plus25Label",
      title: "25+ Label (e.g. 25+)",
      type: "localeString",
      fieldset: "specs",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "atticLabel",
      title: "Attic Label (e.g. Potkrovlje)",
      type: "localeString",
      fieldset: "specs",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "highAtticLabel",
      title: "High Attic Label (e.g. Visoko potkrovlje)",
      type: "localeString",
      fieldset: "specs",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "penthouseLabel",
      title: "Penthouse Label (e.g. Penthouse)",
      type: "localeString",
      fieldset: "specs",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "rentedLabel",
      title: "Rented Label (e.g. Ovaj oglas je iznajmljen)",
      type: "localeString",
      fieldset: "specs",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "reservedLabel",
      title: "Reserved Label (e.g. Ovaj oglas je rezerviran)",
      type: "localeString",
      fieldset: "specs",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "studioApartmentLabel",
      title: "Studio Apartment Label",
      type: "localeString",
      fieldset: "rooms",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "oneRoomLabel",
      title: "One Room Label",
      type: "localeString",
      fieldset: "rooms",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "twoRoomsLabel",
      title: "Two Rooms Label",
      type: "localeString",
      fieldset: "rooms",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "threeRoomsLabel",
      title: "Three Rooms Label",
      type: "localeString",
      fieldset: "rooms",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "fourRoomsLabel",
      title: "Four Rooms Label",
      type: "localeString",
      fieldset: "rooms",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "fiveRoomsLabel",
      title: "Five+ Rooms Label",
      type: "localeString",
      fieldset: "rooms",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "phoneLabel",
      title: "Phone Label (e.g. Telefon)",
      type: "localeString",
      fieldset: "agent",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "emailLabel",
      title: "Email Label (e.g. Email)",
      type: "localeString",
      fieldset: "agent",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "whatsAppLabel",
      title: "WhatsApp Label",
      type: "localeString",
      fieldset: "agent",
      validation: (rule) => rule.required(),
    }),
    // Content
    defineField({
      name: "descriptionTitle",
      title: "Description Title (e.g. Opis nekretnine)",
      type: "localeString",
      fieldset: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "rentalTermsTitle",
      title: "Rental Terms Title (e.g. Uvjeti najma)",
      type: "localeString",
      fieldset: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "noCommissionNote",
      title: "No Commission Note",
      type: "localeString",
      fieldset: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "scheduleViewingTitle",
      title: "Schedule Viewing Title",
      type: "localeString",
      fieldset: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "scheduleViewingText",
      title: "Schedule Viewing Text",
      type: "localeString",
      fieldset: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "locationTitle",
      title: "Location Title (e.g. Lokacija)",
      type: "localeString",
      fieldset: "content",
      validation: (rule) => rule.required(),
    }),
  ],
  preview: {
    prepare() {
      return {
        title: "Listing Details Page Settings",
      };
    },
  },
});
