import { defineField, defineType } from "sanity";
import { SearchIcon } from "@sanity/icons";

export const listingExplorerSection = defineType({
  name: "listingExplorerSection",
  title: "Listing Explorer Section",
  type: "document",
  icon: SearchIcon,
  fieldsets: [
    {
      name: "main",
      title: "Main Titles",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "filterLabels",
      title: "Filter Labels",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "typeOptions",
      title: "Room Selection Options",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "placeholders",
      title: "Input Placeholders",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "header",
      title: "Listing Header & Sort",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "noResults",
      title: "No Results Content",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "statusLabels",
      title: "Status Labels",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "card",
      title: "Listing Card Labels",
      options: { collapsible: true, collapsed: false },
    },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "localeString",
      fieldset: "main",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "locationLabel",
      title: "Location Label",
      type: "localeString",
      fieldset: "filterLabels",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "priceLabel",
      title: "Price Label",
      type: "localeString",
      fieldset: "filterLabels",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "areaLabel",
      title: "Area Label",
      type: "localeString",
      fieldset: "filterLabels",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "roomsLabel",
      title: "Rooms Label",
      type: "localeString",
      fieldset: "filterLabels",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "petFriendlyLabel",
      title: "Pet Friendly Label",
      type: "localeString",
      fieldset: "filterLabels",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "applyButtonLabel",
      title: "Apply Button Label",
      type: "localeString",
      fieldset: "filterLabels",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "minPlaceholder",
      title: "Min Placeholder",
      type: "localeString",
      fieldset: "placeholders",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "maxPlaceholder",
      title: "Max Placeholder",
      type: "localeString",
      fieldset: "placeholders",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "allRoomsLabel",
      title: "All Rooms Label",
      type: "localeString",
      fieldset: "typeOptions",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "studioApartmentLabel",
      title: "Studio Apartment Label",
      type: "localeString",
      fieldset: "typeOptions",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "oneRoomLabel",
      title: "One Room Label",
      type: "localeString",
      fieldset: "typeOptions",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "twoRoomsLabel",
      title: "Two Rooms Label",
      type: "localeString",
      fieldset: "typeOptions",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "threeRoomsLabel",
      title: "Three Rooms Label",
      type: "localeString",
      fieldset: "typeOptions",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "fourRoomsLabel",
      title: "Four Rooms Label",
      type: "localeString",
      fieldset: "typeOptions",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "fiveRoomsLabel",
      title: "Five+ Rooms Label",
      type: "localeString",
      fieldset: "typeOptions",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "allCountiesLabel",
      title: "All Counties Label",
      type: "localeString",
      fieldset: "filterLabels",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "totalResultsLabel",
      title: "Total Results Label",
      type: "localeString",
      fieldset: "header",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "sortNewestLabel",
      title: "Sort Newest Label",
      type: "localeString",
      fieldset: "header",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "sortPriceAscLabel",
      title: "Sort Price Asc Label",
      type: "localeString",
      fieldset: "header",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "sortPriceDescLabel",
      title: "Sort Price Desc Label",
      type: "localeString",
      fieldset: "header",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "noResultsTitle",
      title: "No Results Title",
      type: "localeString",
      fieldset: "noResults",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "noResultsDescription",
      title: "No Results Description",
      type: "localeString",
      fieldset: "noResults",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "rentedLabel",
      title: "Rented Label",
      type: "localeString",
      fieldset: "statusLabels",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "reservedLabel",
      title: "Reserved Label",
      type: "localeString",
      fieldset: "statusLabels",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "detailsCtaText",
      title: "Details CTA Text",
      type: "localeString",
      fieldset: "card",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "monthlyRentSuffix",
      title: "Monthly Rent Suffix",
      type: "localeString",
      fieldset: "card",
      validation: (rule) => rule.required(),
    }),
  ],
  preview: {
    prepare() {
      return {
        title: "Listing Explorer Configuration",
      };
    },
  },
});
