import { defineField, defineType } from "sanity";

export const metHomePage = defineType({
  name: "metHomePage",
  title: "MET Home Page",
  type: "document",
  fieldsets: [
    {
      name: "heroSection",
      title: "Hero Section",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "positioningSection",
      title: "Positioning Section",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "featuredSection",
      title: "Featured Apartments Section",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "whySection",
      title: "Why MET Section",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "landlordSection",
      title: "Landlord Section",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "tenantSection",
      title: "Tenant Section",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "internationalSection",
      title: "International Tenants Section",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "trustSection",
      title: "Trust Section",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "aboutSection",
      title: "About Section",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "listingCards",
      title: "Listing Card Labels",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "seo",
      title: "SEO",
      options: { collapsible: true, collapsed: false },
    },
  ],
  fields: [
    defineField({
      name: "heroTitle",
      title: "Hero Title",
      type: "localeString",
      fieldset: "heroSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroSubtitle",
      title: "Hero Subtitle",
      type: "localeString",
      fieldset: "heroSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroBackgroundImages",
      title: "Hero Background Images",
      type: "array",
      fieldset: "heroSection",
      validation: (rule) => rule.required().min(1).max(3),
      of: [
        {
          type: "object",
          fields: [
            defineField({
              name: "image",
              title: "Image",
              type: "image",
              options: { hotspot: true },
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "imageAlt",
              title: "Image Alt",
              type: "localeString",
              validation: (rule) => rule.required(),
            }),
          ],
          preview: {
            select: {
              title: "imageAlt.hr",
              media: "image",
            },
          },
        },
      ],
    }),
    defineField({
      name: "positioningTitle",
      title: "Positioning Title",
      type: "localeString",
      fieldset: "positioningSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "positioningSubtitle",
      title: "Positioning Subtitle",
      type: "localeString",
      fieldset: "positioningSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "positioningContent",
      title: "Positioning Content",
      type: "localeRichText",
      fieldset: "positioningSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "featuredTitle",
      title: "Featured Title",
      type: "localeString",
      fieldset: "featuredSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "featuredCtaText",
      title: "Featured CTA Text",
      type: "localeString",
      fieldset: "featuredSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "whyTitle",
      title: "Why Title",
      type: "localeString",
      fieldset: "whySection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "whyItems",
      title: "Why Items",
      type: "array",
      fieldset: "whySection",
      validation: (rule) => rule.required().min(1).max(6),
      of: [
        {
          type: "object",
          fields: [
            defineField({
              name: "title",
              title: "Title",
              type: "localeString",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "text",
              title: "Text",
              type: "localeString",
              validation: (rule) => rule.required(),
            }),
          ],
          preview: {
            select: { title: "title.hr" },
          },
        },
      ],
    }),
    defineField({
      name: "landlordTitle",
      title: "Landlord Title",
      type: "localeString",
      fieldset: "landlordSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "landlordContent",
      title: "Landlord Content",
      type: "localeRichText",
      fieldset: "landlordSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "landlordCtaText",
      title: "Landlord CTA Text",
      type: "localeString",
      fieldset: "landlordSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "landlordCtaHref",
      title: "Landlord CTA Href",
      type: "string",
      fieldset: "landlordSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "tenantTitle",
      title: "Tenant Title",
      type: "localeString",
      fieldset: "tenantSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "tenantContent",
      title: "Tenant Content",
      type: "localeRichText",
      fieldset: "tenantSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "tenantCtaText",
      title: "Tenant CTA Text",
      type: "localeString",
      fieldset: "tenantSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "tenantCtaHref",
      title: "Tenant CTA Href",
      type: "string",
      fieldset: "tenantSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "internationalTitle",
      title: "International Title",
      type: "localeString",
      fieldset: "internationalSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "internationalContent",
      title: "International Content",
      type: "localeRichText",
      fieldset: "internationalSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "trustTitle",
      title: "Trust Title",
      type: "localeString",
      fieldset: "trustSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "trustContent",
      title: "Trust Content",
      type: "localeRichText",
      fieldset: "trustSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "aboutTitle",
      title: "About Title",
      type: "localeString",
      fieldset: "aboutSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "aboutContent",
      title: "About Content",
      type: "localeString",
      fieldset: "aboutSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "directorText",
      title: "Director Text",
      type: "localeString",
      fieldset: "aboutSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "directorEducation",
      title: "Director Education",
      type: "localeString",
      fieldset: "aboutSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "directorCredential",
      title: "Director Credential",
      type: "localeString",
      fieldset: "aboutSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "hgkLogoHr",
      title: "HGK Logo HR",
      type: "image",
      options: { hotspot: true },
      fieldset: "aboutSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "hgkLogoEn",
      title: "HGK Logo EN",
      type: "image",
      options: { hotspot: true },
      fieldset: "aboutSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "hgkLogoAlt",
      title: "HGK Logo Alt",
      type: "localeString",
      fieldset: "aboutSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "hgkText",
      title: "HGK Text",
      type: "localeString",
      fieldset: "aboutSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "apartmentCardCtaText",
      title: "Apartment Card CTA Text",
      type: "localeString",
      fieldset: "listingCards",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "monthlyRentSuffix",
      title: "Monthly Rent Suffix",
      type: "localeString",
      fieldset: "listingCards",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "emptyFeaturedText",
      title: "Empty Featured Text",
      type: "localeString",
      fieldset: "listingCards",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "metaTitle",
      title: "Meta Title",
      type: "localeString",
      fieldset: "seo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "metaDescription",
      title: "Meta Description",
      type: "localeString",
      fieldset: "seo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "metaOgImage",
      title: "Open Graph Image",
      type: "image",
      options: { hotspot: true },
      fieldset: "seo",
    }),
  ],
  preview: {
    prepare() {
      return {
        title: "MET Home Page",
      };
    },
  },
});
