import { defineField, defineType } from "sanity";

export const submitApartmentPage = defineType({
  name: "submitApartmentPage",
  title: "Submit Apartment Page",
  type: "document",
  fieldsets: [
    {
      name: "heroSection",
      title: "Hero Section",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "formSection",
      title: "Form Section",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "seo",
      title: "SEO",
      options: { collapsible: true, collapsed: false },
    },
  ],
  fields: [
    defineField({
      name: "heroTitle",
      title: "Hero Title",
      type: "localeString",
      fieldset: "heroSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroDescriptionText",
      title: "Hero Description Text",
      type: "localeString",
      fieldset: "heroSection",
    }),
    defineField({
      name: "heroBackgroundImage",
      title: "Hero Background Image",
      type: "image",
      options: { hotspot: true },
      fieldset: "heroSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroBackgroundImageAlt",
      title: "Hero Background Image Alt",
      type: "localeString",
      fieldset: "heroSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "nameLabel",
      title: "Name Label",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "namePlaceholder",
      title: "Name Placeholder",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "nameRequiredError",
      title: "Name Required Error",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "phoneLabel",
      title: "Phone Label",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "phonePlaceholder",
      title: "Phone Placeholder",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "phoneRequiredError",
      title: "Phone Required Error",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "emailLabel",
      title: "Email Label",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "emailPlaceholder",
      title: "Email Placeholder",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "emailRequiredError",
      title: "Email Required Error",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "emailInvalidError",
      title: "Email Invalid Error",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "districtLabel",
      title: "District Label",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "districtPlaceholder",
      title: "District Placeholder",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "districtRequiredError",
      title: "District Required Error",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "areaLabel",
      title: "Area Label",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "areaPlaceholder",
      title: "Area Placeholder",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "areaRequiredError",
      title: "Area Required Error",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "roomsLabel",
      title: "Rooms Label",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "roomsPlaceholder",
      title: "Rooms Placeholder",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "roomsRequiredError",
      title: "Rooms Required Error",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "rentPriceLabel",
      title: "Rent Price Label",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "rentPricePlaceholder",
      title: "Rent Price Placeholder",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "rentPriceRequiredError",
      title: "Rent Price Required Error",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "descriptionLabel",
      title: "Description Label",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "descriptionPlaceholder",
      title: "Description Placeholder",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "descriptionRequiredError",
      title: "Description Required Error",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "photosLabel",
      title: "Photos Label",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "photosHelpText",
      title: "Photos Help Text",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "sendButtonText",
      title: "Send Button Text",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "sendingButtonText",
      title: "Sending Button Text",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "successMessage",
      title: "Success Message",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "errorMessage",
      title: "Error Message",
      type: "localeString",
      fieldset: "formSection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "metaTitle",
      title: "Meta Title",
      type: "localeString",
      fieldset: "seo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "metaDescription",
      title: "Meta Description",
      type: "localeString",
      fieldset: "seo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "metaOgImage",
      title: "Open Graph Image",
      type: "image",
      options: { hotspot: true },
      description:
        "Image displayed when the page is shared on social media platforms. Recommended dimensions: 1200x630 px.",
      fieldset: "seo",
    }),
  ],
  preview: {
    prepare() {
      return {
        title: "Submit Apartment Page",
      };
    },
  },
});
